### ISSUE TITLE
Change crop dimension label

### ISSUE THREAD

**Issue by davedbase** [uploadcare/uploadcare-widget#799]
I was wondering if it's possible to change the the crop options label? Rather than listing the options as ratios we want to more neatly display the options available to the suer ie. Portrait, Landscape, Square etc. Reviewing the codebase it seems that isn't totally possible right now from the crop property. Am I correct in assuming this? If so, can we expect the roadmap to count for this feature any time soon?

Thanks!!

**Comment by optlsnd** [comment]
Hi @davedbase, you can do this with some CSS. For example, if you have 2 presets:

```css
.uploadcare--button_icon {
  width: 100px;
}

.uploadcare--crop-sizes__item:nth-child(1)::after {
  content: 'Vertical'
}

.uploadcare--crop-sizes__item:nth-child(2)::after {
  content: 'Horizontal'
}
```

You can check out a live version [here](https://codepen.io/optlsnd/pen/GbYvPN).
